Development
scade-platform/FusionLocalAuth pull request #1
Opened 2022-01-04 08:40 UTC by 6vedant

API protocol for FusionLocalAuth

2022-01-10 15:48 UTC, gr-markin requested changes

2022-01-10 15:48 UTC, gr-markin commented on FusionLocalAuth/Sources/FusionLocalAuth_Common/LocalAuthManager.swift
> +    func onAuthSuccess() -> Void
The API is fine, the only thing is that the callback functions cannot be defined this way most likely. The manager protocol is just an API that will be implemented by both parts: iOS and Android, hence, the library will contain the manager implementation at the end that will be used by an end-user. The callbacks, in turn, should be implemented by the end-user itself. That's why we either should add something like a "delegate" protocol that will be implemented by the end-user and passed to the manager, or add a callback parameter to every request function. I would like to use the auth manager this way (just one callback param to receive an err in case of an error):

```
manager.requestDeviceAuthentication(title: "Auth", reasonTitle: "I need your password", cancelText: "Don't care") { err in
  if let error = err {
    // do something
    return
  }
  // request accepted
}
```

2022-01-11 12:22 UTC, 6vedant commented on FusionLocalAuth/Sources/FusionLocalAuth_Common/LocalAuthManager.swift
> +    func onAuthSuccess() -> Void
Ok, will do necessary changes asap. Thanks.

2022-01-12 16:13 UTC, gr-markin approved these changes

2022-01-12 16:13 UTC, merged